class ReservationStatus:
    STARTED = 1
    IN_PROCESS = 2
    ERROR = 3
    SUCCESSFUL_PAYMENT = 4
    CANCELED_PAYMENT = 5
    REJECTED_PAYMENT = 6
    REJECTED_BY_LOCAL = 7
    CONFIRMED = 8
    NO_CONFIRMED = 10
