import os


class Settings:
    ENVIRONMENT = os.getenv("ENVIRONMENT")
    MAPBOX_URL = os.getenv("MAPBOX_URL")
    CONNECTION_STRING_DB = os.getenv("DB_CONN")
    CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
    CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
    CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
    KHIPU_SECRET_ID = os.getenv("KHIPU_SECRET_ID")
    KHIPU_RECEIVER_ID = os.getenv("KHIPU_RECEIVER_ID")
    KHIPU_NOTIFY_URL = os.getenv("KHIPU_RECEIVER_ID")
    KHIPU_RETURN_URL = os.getenv("KHIPU_RECEIVER_ID")
    KHIPU_CANCEL_URL = os.getenv("KHIPU_RECEIVER_ID")
    KHIPU_PICTURE_URL = os.getenv("KHIPU_RECEIVER_ID")
