name: Development deployment in Heroku

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          dontautocreate: false
          usedocker: true
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_PROD_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}