name: Dev deploy Heroku

on:
  # pull_request:
  #   types: opened
  #   branches:
  #     - develop
  push:
    branches: fix-env-easier-way
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          echo ENVIRONMENT="Development" >> .env
          echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} >> .env
          echo CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} >> .env
          echo CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} >> .env
          echo JWT_KEY=${{ secrets.JWT_KEY }} >> .env
          echo MAPBOX_API=${{ secrets.MAPBOX_API }} >> .env
          echo MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }} >> .env
          echo EMAIL_HOST=${{ secrets.EMAIL_HOST }} >> .env
          echo EMAIL_PORT=${{ secrets.EMAIL_PORT }} >> .env
          echo EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo EMAIL_ENCODING=${{ secrets.EMAIL_ENCODING }} >> .env
          echo ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }} >> .env
          cat .env
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_DEV_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          dontautocreate: false
          usedocker: true
  discord-notification:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_BACKEND_DEV_PIPELINE }}
          username: GitHub Actions
          title: "A new version was deployed in DEV/QA"
          description: "Deployed in Heroku"