name: Prod deploy Heroku

on:
  push:
    branches:
      - main
jobs:
  create-envfile:
    runs-on: ubuntu-18.04
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          ENVIRONMENT: "Production"
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          KHIPU_SECRET_ID: ${{ secrets.KHIPU_SECRET_ID }}
          KHIPU_RECEIVER_ID: ${{ secrets.KHIPU_RECEIVER_ID }}
          KHIPU_NOTIFY_URL: ${{ secrets.KHIPU_NOTIFY_URL }}
          KHIPU_RETURN_URL: ${{ secrets.KHIPU_RETURN_URL }}
          KHIPU_CANCEL_URL: ${{ secrets.KHIPU_CANCEL_URL }}
          KHIPU_PICTURE_URL: ${{ secrets.KHIPU_PICTURE_URL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          MAPBOX_API: ${{ secrets.MAPBOX_API }}
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_ENCODING: ${{ secrets.EMAIL_ENCODING }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_PROD_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          dontautocreate: false
          usedocker: true
  discord-notification:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_BACKEND_PROD_PIPELINE }}
          username: GitHub Actions
          title: "A new version was deployed in PRODUCTION"
          description: "Deployed in Heroku"